apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neobank

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres/postgres.yaml
  - redis/redis.yaml
  - auth/deployment.yaml
  - account/deployment.yaml
  - transaction/deployment.yaml
  - frontend/deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: neobank
